const express = require('express');
const router = express.Router();
const crypto = require('crypto');
const ReferralLink = require('../models/ReferralLink');
const Product = require('../models/RefProduct');
const ClickLog = require('../models/ClickLog');
const DownloadLog = require('../models/DownloadLog');
const { protect } = require('../middleware/auth');
const { syncLinkToMarketing, deleteLinkFromMarketing } = require('../utils/marketingSync');


function generateNanoId(size = 5) {
  const alphabet = '1234567890abcdefghijklmnopqrstuvwxyz';
  let id = '';
  const bytes = crypto.randomBytes(size);
  for (let i = 0; i < size; i++) {
    id += alphabet[bytes[i] % alphabet.length];
  }
  return id;
}

// @route   GET /api/links
// @desc    Get all links generated by the authenticated user with click & download analytics
router.get('/', protect, async (req, res) => {
  try {
    const links = await ReferralLink.find({ user: req.user.id })
      .populate('product')
      .sort({ createdAt: -1 })
      .lean();

    const host = req.get('host');
    const protocol = req.protocol;
    const backendUrl = process.env.REFERRAL_BASE_URL || `${protocol}://${host}`;

    const enhancedLinks = await Promise.all(
      links.map(async (link) => {
        // Click analytics
        const desktopClicks = await ClickLog.countDocuments({
          referralLink: link._id,
          deviceType: 'desktop',
        });
        const androidClicks = await ClickLog.countDocuments({
          referralLink: link._id,
          deviceType: 'android',
        });
        const iosClicks = await ClickLog.countDocuments({
          referralLink: link._id,
          deviceType: 'ios',
        });
        const uniqueClicksCount = await ClickLog.countDocuments({
          referralLink: link._id,
          isUnique: true,
        });
        const uniqueClicks = Math.max(link.uniqueClicks || 0, uniqueClicksCount);
        const totalClicks = link.clicks || desktopClicks + androidClicks + iosClicks;

        // Download / Install analytics
        const androidDownloads = await DownloadLog.countDocuments({
          referralLink: link._id,
          platform: 'android',
        });
        const iosDownloads = await DownloadLog.countDocuments({
          referralLink: link._id,
          platform: 'ios',
        });

        return {
          ...link,
          uniqueClicks,
          fullUrl: `${backendUrl}/r/${link.code}`,
          deviceStats: {
            desktop: desktopClicks,
            android: androidClicks,
            ios: iosClicks,
            total: totalClicks,
            unique: uniqueClicks,
          },
          downloadStats: {
            android: androidDownloads,
            ios: iosDownloads,
            total: link.downloads || androidDownloads + iosDownloads,
          },
        };
      })
    );

    res.json({ success: true, links: enhancedLinks });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// @route   GET /api/links/activity
// @desc    Get chronological referral activity feed (clicks and verified downloads)
router.get('/activity', protect, async (req, res) => {
  try {
    const userLinks = await ReferralLink.find({ user: req.user.id }).select('_id');
    const linkIds = userLinks.map((l) => l._id);

    const [clicks, downloads] = await Promise.all([
      ClickLog.find({ referralLink: { $in: linkIds } })
        .populate('product', 'name slug')
        .sort({ createdAt: -1 })
        .limit(50)
        .lean(),
      DownloadLog.find({ referralLink: { $in: linkIds } })
        .populate('product', 'name slug')
        .sort({ createdAt: -1 })
        .limit(50)
        .lean(),
    ]);

    const activity = [
      ...clicks.map((c) => ({
        id: c._id,
        type: 'click',
        title: `${c.product?.name || 'Product'} Link Click`,
        productName: c.product?.name || 'Unknown Product',
        productSlug: c.product?.slug || '',
        code: c.code,
        deviceType: c.deviceType,
        ip: c.ip ? c.ip.replace(/(\d+)\.(\d+)\.(\d+)\.(\d+)/, '$1.$2.***.***') : 'Unknown',
        targetUrl: c.targetUrl,
        isUnique: c.isUnique,
        attributionMethod: 'web_redirect',
        timestamp: c.createdAt,
      })),
      ...downloads.map((d) => ({
        id: d._id,
        type: 'download',
        title: `${d.product?.name || 'Product'} App Installed`,
        productName: d.product?.name || 'Unknown Product',
        productSlug: d.product?.slug || '',
        code: d.code,
        deviceType: d.platform,
        platform: d.platform,
        ip: d.ip ? d.ip.replace(/(\d+)\.(\d+)\.(\d+)\.(\d+)/, '$1.$2.***.***') : 'Unknown',
        attributionMethod: d.attributionMethod,
        isUnique: true,
        timestamp: d.createdAt,
      })),
    ].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

    res.json({ success: true, activity });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// @route   POST /api/links
// @desc    Generate a referral link under user credentials
router.post('/', protect, async (req, res) => {
  try {
    const { productId } = req.body;

    if (!productId) {
      return res.status(400).json({ error: 'Product ID is required' });
    }

    const product = await Product.findById(productId);
    if (!product) {
      return res.status(404).json({ error: 'Project not found' });
    }

    let link = await ReferralLink.findOne({
      user: req.user.id,
      product: productId,
    }).populate('product');

    const host = req.get('host');
    const protocol = req.protocol;
    const backendUrl = process.env.REFERRAL_BASE_URL || `${protocol}://${host}`;

    if (link) {
      return res.json({
        success: true,
        message: 'Link already exists for this project',
        link: {
          ...link.toObject(),
          fullUrl: `${backendUrl}/r/${link.code}`,
        },
      });
    }

    const prodSlug = (product.slug || 'ref').toLowerCase().replace(/[^a-z0-9]/g, '');
    const userSlug = (req.user.name || req.user.userId || 'partner').toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 10);
    const randNum = Math.floor(10000 + Math.random() * 90000);
    let code = `${prodSlug}-ref-${userSlug}-${randNum}`;
    while (await ReferralLink.findOne({ code })) {
      const newRand = Math.floor(10000 + Math.random() * 90000);
      code = `${prodSlug}-ref-${userSlug}-${newRand}`;
    }

    link = await ReferralLink.create({
      code,
      user: req.user.id,
      userId: req.user.userId,
      product: productId,
      clicks: 0,
      uniqueClicks: 0,
      downloads: 0,
    });

    await link.populate('product');

    // Automatically sync to marketing_links so https://admin.uwo24.com/r/:code redirects immediately
    syncLinkToMarketing(link, link.product).catch((err) =>
      console.warn('[Referral Links] Background sync error:', err.message)
    );

    res.status(201).json({
      success: true,
      message: 'Referral link generated successfully!',
      link: {
        ...link.toObject(),
        fullUrl: `${backendUrl}/r/${link.code}`,
      },
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// @route   DELETE /api/links/:id
// @desc    Delete a referral link (and its click/download logs)
router.delete('/:id', protect, async (req, res) => {
  try {
    const link = await ReferralLink.findOne({
      _id: req.params.id,
      $or: [
        { user: req.user.id },
        { userId: req.user.userId },
      ],
    });
    if (!link) {
      return res.status(404).json({ error: 'Link not found or not authorized' });
    }

    // Remove associated logs
    await ClickLog.deleteMany({
      $or: [{ referralLink: link._id }, { code: link.code }],
    });
    await DownloadLog.deleteMany({
      $or: [{ referralLink: link._id }, { code: link.code }],
    });
    await ReferralLink.findByIdAndDelete(link._id);

    // Remove from marketing_links in unified_service_db as well
    deleteLinkFromMarketing(link.code).catch((err) =>
      console.warn('[Referral Links] Background delete sync error:', err.message)
    );

    res.json({ success: true, message: 'Referral link deleted successfully' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
