#!/bin/sh
set -e

# Default PORT to 8080 if not passed by Cloud Run
export PORT="${PORT:-8080}"

echo "=================================================="
echo "🚀 Starting UWO User Referral Dashboard Container"
echo "🌐 Cloud Run PORT: ${PORT}"
echo "=================================================="

# Substitute ${PORT} in nginx configuration template
envsubst '${PORT}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf

# Generate runtime env-config.js for React SPA
CONFIG_FILE="/usr/share/nginx/html/env-config.js"
echo "// Auto-generated by container entrypoint at $(date -u)" > "$CONFIG_FILE"
echo "window._env_ = {" >> "$CONFIG_FILE"

# Extract and inject all VITE_ and UWO_ environment variables
env | grep -E '^(VITE_|UWO_)' | while IFS= read -r line; do
  key=$(echo "$line" | cut -d '=' -f 1)
  value=$(echo "$line" | cut -d '=' -f 2-)
  # Escape double quotes and backslashes for valid JSON / JS
  escaped_value=$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
  echo "  \"$key\": \"$escaped_value\"," >> "$CONFIG_FILE"
done

echo "};" >> "$CONFIG_FILE"

# Also ensure /user/env-config.js exists directly
mkdir -p /usr/share/nginx/html/user
cp -f "$CONFIG_FILE" /usr/share/nginx/html/user/env-config.js

echo "📋 Runtime Environment Configuration generated:"
cat "$CONFIG_FILE"
echo ""
echo "🌟 Starting Nginx web server..."
exec nginx -g 'daemon off;'
